---
 - hosts: all
   become: true
   tasks:
   - name: Install apache via ansible
     yum:
        name: httpd
        status: latest

   - name: Install postfix
     yum:
        name: postfix
        status: latest


        
    
