---
 - hosts: all
   become: true
   vars:
     web_server: httpd
     ftp_server: vsftpd
     nfs_server: nfs-utils
   
 - name: Start httpd nfs vsftpd services
   service:
     name:  "{{ web_server }}" 
     state: started
        

 
   
